# get table by table id
GET http://localhost:4500/get-table/id_table
Accept: application/json
###

# post new table
POST http://localhost:4500/upload-table/1
Content-Type: application/json

{
    "header": [
        "col1",
        "col2",
        "col3",
        "col4",
        "col5",
        "col6",
        "col7"
    ],
    "body": [
        ["TATIANA CAROLINA", 1, 1, 1, 1, 4, 1],
        ["YEIMI ATENCIO", 2, 4, 1, 3, 10, 2],
        ["ALEJANDRA MARTINEZ", 7, 2, 2, 3, 14, 3],
        ["YURANIS PACHECO", 5, 3, 12, 4, 24, 4],
        ["LINA DOVAL", 8, 6, 4, 3, 12, 5],
        ["LINA GARCIA", 6, 10, 5, 5, 26, 6],
        ["JHANA ARROYO", 9, 9, 9, 9, 34, 7],
        ["CRISTINA CARDONA", 12, 11, 10, 5, 38, 8],
        ["GRACE NARANJO", 14, 5, 14, 5, 40, 9],
        ["LORENA FUENTES", 20, 5, 15, 11, 43, 10],
        ["MARIA ALEJANDRA", 15, 14, 7, 11, 47, 11],
        ["LILIANA NEGRETE", 13, 13, 12, 11, 49, 12],
        ["DAYANA ARGEL", 13, 12, 13, 11, 50, 13],
        ["DAYSSI PARRA", 17, 16, 11, 8, 51, 14],
        ["LEIDY SANCHEZ", 4, 17, 16, 15, 52, 15],
        ["WENDY AYAZO", 3, 20, 12, 17, 52, 15],
        ["ISABELLA LOZANO", 21, 12, 17, 16, 59, 17],
        ["DAIRYS FURNIELES", 15, 21, 15, 20, 61, 18],
        ["MARIED BLANQUICET", 15, 21, 18, 16, 73, 19],
        ["DINA TEHERAN", 19, 18, 16, 16, 73, 19],
        ["MARIA FERNANDA COL", 18, 19, 21, 18, 76, 21]
    ]
}
###

# update a row in a table by id 
PUT  http://localhost:4500/update-table/2
Content-Type: application/json

[
    ["MARIA FERNANDA COLasdf", 12, 13, 11, 22, 99, 11]
]

###

# delete all table by table id 
DELETE http://localhost:4500/delete-table/:id
Accept: application/json
###

# delete a specific row by table id and row id 
DELETE http://localhost:4500/delete-row-table/1/3
Accept: application/json






